name: Trivy Test
on: workflow_dispatch 

jobs:
  build:
    permissions:
        id-token: write
        contents: read
        
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2