# name: Trivy Test
# on: workflow_dispatch 

# jobs:
#   build:
#     permissions:
#         id-token: write
#         contents: read
        
#     runs-on: ubuntu-latest
#     defaults:
#         run:
#           shell: bash
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

name: Trivy Test
on: workflow_dispatch 
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run static analysis
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,secret,config'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'code'